-- One lead per submission.
--
-- Ingestion used to resolve an incoming submission to an existing lead by
-- (organization_id, normalized_phone) and merge into it. That is right for a
-- source only the brokerage's own staff feeds. It is wrong for a connected form,
-- which is published publicly: two different prospects legitimately arrive on
-- one shared number — a couple, a family line, a colleague filling a form in for
-- someone else — and the merge overwrote the first person's name, budget and
-- timeline with the second's. The brokerage then called one prospect and never
-- learned the other existed. A submission is an intent to be contacted, and
-- every one of them now gets its own row.
--
-- The evidence was never lost: webhook_events.dedupe_key is Tally's eventId, so
-- each submission was already a distinct delivery. Only the leads table
-- collapsed them.
--
-- Dropping this index is what allows two leads to share a phone number.
-- Idempotency does NOT depend on it and is unchanged: a retried delivery is
-- stopped by webhook_events_source_dedupe_uniq at the door, and by the unique
-- lead_submissions.webhook_event_id behind it. Neither keys off the prospect's
-- phone number, so neither weakens here.
--
-- What replaces it is a read-side signal, not a write-side constraint: the
-- leads API reports how many leads in the org share a contact's normalized
-- phone or email, and the pipeline badges those rows "repeat contact". The
-- duplicate stays visible without a second person's data being destroyed to
-- show it.
DROP INDEX IF EXISTS leads_org_phone_uniq;

-- Both of these already exist as plain indexes (idx_leads_phone, idx_leads_email)
-- and are now load-bearing for that repeat-contact lookup rather than for merge
-- resolution. Nothing to add; this note is here so a future reader does not
-- mistake them for leftovers of the dropped constraint.
